### ISSUE TITLE
My Overall Comments

### ISSUE THREAD

**Issue by desgarcia** [alfredocarella/simplebendingpractice#5]
@alfredocarella 
- I think this software is neat and I could picture it being used by future students and teachers. I appreciate the Welcome to BeamBending (https://alfredocarella.github.io/simplebendingpractice/index.html), and found it very helpful in reviewing BeamBending as 'an instructor'. 

- You refer to an applet for more info to your audience for a system in equilibrium (https://www.edumedia-sciences.com/en/media/80-action-reaction-principle), but this page requires a subscription - is there any other open source page you can use? 

- Can you provide some of the comments from the students from Autumn 2018 in the 'Recent Uses' section of the paper? 

- Again, add more references including similar statics or engineering software.

**Comment by alfredocarella** [comment]
@desgarcia 

The mentioned applet in the webpage requiring a subscription has been replaced by a (freely available) video from Khan Academy, which is equally (or more) useful.

The student comments I received were oral, informal and unspecific. Real concrete examples are:
* "I found it easy to check my answers to the practice problems"
* "Playing around with the load shapes helped me visualize how distributed loads, shear force and bending moment are correlated"

However, I have no objective reason to assume that this feedback is representative or complete, since:
1. I did not receive a lot of comments (about a dozen, which is roughly 10 percent of the class), and
2. the comments are likely to be biased in a positive directions (few students spontaneously approach a teacher to tell him that his pet-project is terrible).

The references are addressed in the previous issue: #4
